mysite/urls.py
from django.contrib import admin
from django.urls import include, path
# from django.views.generic import RedirectView

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("trans19.urls")),
    path('accounts/', include('django.contrib.auth.urls')),
]

trans19/urls.py
from django.urls import path
from . import views

app_name = 'trans19'

urlpatterns = [
    path('', views.index, name='index'),
    path('locations/', views.locations, name='locations'),
    path('patients/', views.patients, name='patients'),
    path('patients/<int:patient_id>/', views.detail, name='detail'),
    path('patients/new/', views.PatientCreate.as_view(), name='patient_new'),
    path('patients/<int:pk>/edit', views.PatientUpdate.as_view(), name='patient_edit'),
    path('patients/<int:pk>/delete', views.PatientDelete.as_view(), name='patient_delete'),
    path('patients/search/', views.SearchConnectionsView, name='search_connections'),
    path('locations/new', views.location_new, name='location_new'),
    path('locations/<int:pk>/edit', views.location_edit, name='location_edit'),
    path('locations/<int:pk>/delete', views.LocationDelete.as_view(), name='location_delete'),
]

trans19/models.py
from django.db import models
from django.urls import reverse
from datetime import date

class Patient(models.Model):
  patient_name = models.CharField(
    "Name", 
    max_length=200, 
    # help_text="Name of the Patient"
  )
  patient_id = models.CharField(
    "Patient Identity Document Number", 
    max_length=10, 
    # help_text="Identity Document Number", 
    null=True, 
    blank=True
  )
  date_of_birth = models.DateField(
    "Date of Birth", 
    null=True, 
    blank=True
  )
  date_case_confirmed = models.DateField(
    "Date Case Confirmed", 
    null=False, 
    blank=False, 
    default=date.today
  )
  case_number = models.IntegerField(
    "Case Number", 
    primary_key=True,
    null=False,
    blank=False, 
    # default=0, #Patient.objects.all().count(),
    # help_text="The case number of the Patient"
  )

  def __str__(self):
    return self.patient_name+" #"+str(self.case_number)

  def get_absolute_url(self):
      """Returns the url to access a particular author instance."""
      return reverse('detail', args=[str(self.case_number)])

class Location(models.Model):
  location_name = models.CharField("Location Visited", max_length=200, help_text="Name of the Location", blank=True)
  DISTRICT_CHOICES = [
    ('Hong Kong Island', (
            ('Central and Western', 'Central and Western'),
            ('Eastern', 'Eastern'),
            ('Southern', 'Southern'),
            ('Wan Chai', 'Wan Chai'),
        )
    ),
    ('Kowloon', (
            ('Sham Shui Po', 'Sham Shui Po'),
            ('Kowloon City', 'Kowloon City'),
            ('Kwun Tong', 'Kwun Tong'),
            ('Wong Tai Sin', 'Wong Tai Sin'),
            ('Yau Tsim Mong', 'Yau Tsim Mong'),
        )
    ),
    ('New Teritories', (
            ('Islands', 'Islands'),
            ('Kwai Tsing', 'Kwai Tsing'),
            ('North', 'North'),
            ('Sai Kung', 'Sai Kung'),
            ('Sha Tin', 'Sha Tin'),
            ('Tai Po', 'Tai Po'),
            ('Tsuen Wan', 'Tsuen Wan'),
            ('Tuen Mun', 'Tuen Mun'),
            ('Yuen Long', 'Yuen Long'),
        )
    ),
  ]
  district = models.CharField("District", max_length=200, choices=DISTRICT_CHOICES , help_text="District of the Location", default="Central and Western")
  address = models.CharField("Address", max_length=200, help_text="Address of the Location", blank=True, null=True)
  x_coord = models.FloatField("X Coord", help_text="X Coordiates/Longitude of the location", default=0)
  y_coord = models.FloatField("Y Coord", help_text="Y Coordiates/Latitude of the location", default=0)
  def __str__(self):
    return self.location_name

class Visit(models.Model):
  patient = models.ForeignKey(Patient, on_delete=models.CASCADE)
  location = models.ForeignKey(Location, on_delete=models.CASCADE)
  date_from = models.DateField("Date From", default=date.today)
  date_to = models.DateField("Date To", default=date.today)
  detail = models.CharField(max_length=65536, null=True, blank=True)
  CATEGORY_CHOICES = (
    (u'r', u'Residence'),
    (u'w', u'Workplace'),
    (u'v', u'Visit'),
    (u's', u'School'),
  )
  category = models.CharField("Category", max_length=1, choices=CATEGORY_CHOICES, default="v")
  def __str__(self):
    return self.location.location_name+" ("+str(self.date_from)+" - "+str(self.date_to)+")"
  def get_absolute_url(self):
    return reverse('travelhistory-detail', args=[str(self.id)])

trans19/forms.py
from django import forms
from .models import Patient, Visit, Location
from django.forms import inlineformset_factory
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Layout, Field, Fieldset, Div, HTML, ButtonHolder, Submit
from .custom_layout_object import *


class LocationForm(forms.ModelForm):
    class Meta:
        model = Location
        fields = '__all__'


class DateInput(forms.DateInput):
    input_type = 'date'


class VisitForm(forms.ModelForm):
    class Meta:
        model = Visit
        fields = '__all__'
        widgets = {
            'date_from': DateInput(),
            'date_to': DateInput(),
        }


PatientFormSet = inlineformset_factory(
    Patient,
    Visit,
    form=VisitForm,
    extra=1,
    can_delete=True,
)


class PatientForm(forms.ModelForm):

    class Meta:
        model = Patient
        exclude = ()
        widgets = {
            'date_case_confirmed': DateInput(),
            'date_of_birth': DateInput(),
        }

    def __init__(self, *args, **kwargs):
        super(PatientForm, self).__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.form_tag = True
        self.helper.form_class = 'form-horizontal'
        self.helper.label_class = 'col-md-3 create-label'
        self.helper.field_class = 'col-md-9'
        self.helper.layout = Layout(
            Div(
                Field('patient_name'),
                Field('patient_id'),
                Field('date_of_birth'),
                Field('date_case_confirmed'),
                Field('case_number'),
                Fieldset('Add Visits',
                        Formset('visits')),
                HTML("<br>"),
                ButtonHolder(Submit('submit', 'Save')),
                )
            )

trans19/views.py
from django.shortcuts import get_object_or_404, render, redirect
from django.urls import reverse_lazy
from django.db import transaction
from django.views.generic.edit import CreateView, UpdateView, DeleteView


from .models import Patient, Location, Visit
from .forms import LocationForm, PatientForm, PatientFormSet

from datetime import timedelta

def index(request):
    num_cases = Patient.objects.all().count()
    context = {"num_cases": num_cases, "index": "active"}
    return render(request, 'trans19/index.html', context)


def locations(request):
    latest_location_list = Location.objects.order_by('location_name')[:20]
    context = {'latest_location_list': latest_location_list, "location_tab": "active"}
    return render(request, 'trans19/locations.html', context)


def patients(request):
    latest_patient_list = Patient.objects.order_by('case_number')[:20]
    context = {'latest_patient_list': latest_patient_list, "patient_tab": "active"}
    return render(request, 'trans19/patients.html', context)


def detail(request, patient_id):
    patient = get_object_or_404(Patient, pk=patient_id)
    return render(request, 'trans19/detail.html', {'patient': patient})


def location_new(request):
    if request.method == "POST":
        form = LocationForm(request.POST)
        if form.is_valid():
            location = form.save(commit=False)
            location.save()
            return redirect('trans19:locations')
    else:
        form = LocationForm()
    return render(request, 'trans19/addLocation.html', {'form': form, "new_location_tab": "active"})


def location_edit(request, pk):
    location = get_object_or_404(Location, pk=pk)
    if request.method == "POST":
        form = LocationForm(request.POST, instance=location)
        if form.is_valid():
            location = form.save(commit=False)
            location.save()
            return redirect('trans19:locations')
    else:
        form = LocationForm(instance=location)
    return render(request, 'trans19/addLocation.html', {'form': form})


class LocationDelete(DeleteView):
    model = Location
    template_name = 'trans19/deleteLocation.html'
    success_url = reverse_lazy('trans19:locations')


class PatientCreate(CreateView):
    model = Patient
    template_name = 'trans19/addPatient.html'
    form_class = PatientForm
    success_url = None

    def get_context_data(self, **kwargs):
        data = super(PatientCreate, self).get_context_data(**kwargs)
        if self.request.POST:
            data['visits'] = PatientFormSet(self.request.POST)
        else:
            data['visits'] = PatientFormSet()
        data["new_patient_tab"] = "active"
        data['form'] = PatientForm(initial={"case_number": Patient.objects.all().count()})
        return data

    def form_valid(self, form):
        context = self.get_context_data()
        visits = context['visits']
        with transaction.atomic():
            form.instance.created_by = self.request.user
            self.object = form.save()
            if visits.is_valid():
                visits.instance = self.object
                visits.save()
        return super(PatientCreate, self).form_valid(form)

    def get_success_url(self):
        return reverse_lazy('trans19:patients')


class PatientUpdate(UpdateView):
    model = Patient
    template_name = 'trans19/addPatient.html'
    form_class = PatientForm

    def get_context_data(self, **kwargs):
        data = super(PatientUpdate, self).get_context_data(**kwargs)
        if self.request.POST:
            data['visits'] = PatientFormSet(self.request.POST, instance=self.object)
        else:
            data['visits'] = PatientFormSet(instance=self.object)
        return data

    def form_valid(self, form):
        context = self.get_context_data()
        visits = context['visits']
        with transaction.atomic():
            form.instance.created_by = self.request.user
            self.object = form.save()
            if visits.is_valid():
                visits.instance = self.object
                visits.save()
        return super(PatientUpdate, self).form_valid(form)

    def get_success_url(self):
        return reverse_lazy('trans19:patients')


class PatientDelete(DeleteView):
    model = Patient
    template_name = 'trans19/deletePatient.html'
    success_url = reverse_lazy('trans19:patients')


def SearchConnectionsView(request):
    patient_case = request.GET.get('case_number')
    time_window = request.GET.get('time_window')
    if time_window:
        time_window = int(time_window)
    context = {"patient": patient_case, "connection_tab": "active"}
    unfortunate_list = Visit.objects.none()
    visit_list = Visit.objects.filter(patient__case_number=patient_case).values(
        "location", "date_from", "date_to")
    for v in visit_list:
        unfortunate_list = unfortunate_list | Visit.objects.filter(
            location=v["location"]
            ).filter(
                date_from__range=(
                    v["date_from"] - timedelta(days=time_window),
                    v["date_to"] + timedelta(days=time_window)
                )
            ) | Visit.objects.filter(
                location=v["location"]).filter(date_to__range=(
                    v["date_from"] - timedelta(days=time_window),
                    v["date_to"] + timedelta(days=time_window)
                )
            )
    context['potential_patient_list'] = unfortunate_list.exclude( patient__case_number=patient_case)
    context['selected_patient'] = Patient.objects.filter(case_number=patient_case).values( "patient_name", "date_case_confirmed", "case_number")
    context['selected_patient_visit'] = Visit.objects.filter(patient__case_number=patient_case)

    return render(request, 'trans19/searchConnections.html', context)

trans19/templates/trans19/layouts/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <link href="https://fonts.googleapis.com/css?family=Nunito:200,300,400,700&display=swap" rel="stylesheet">
        <link rel="stylesheet" href="{% static 'trans19/style.css' %}">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.0/css/bootstrap.min.css" integrity="sha384-PDle/QlgIONtM1aqA2Qemk5gPOE7wFq8+Em+G/hmo5Iq0CCmYZLv3fVRDJ4MMwEA" crossorigin="anonymous">
        <title>Trans19 - {% block title %}{% endblock %}</title>
        <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.0/js/bootstrap.min.js" integrity="sha384-7aThvCh9TypR7fIc2HV4O/nFMVCBwyIUKL8XCtKE+8xgCgl/PQGuFsvShjr74PBp" crossorigin="anonymous"></script>
    </head>
<body>
    {% include 'trans19/layouts/navbar.html' %}
    {% block content %}{% endblock %}

    

</body>
</html>

trans19/templates/trans19/layouts/navbar.html
{% load static %}
<nav class="navbar navbar-expand-md navbar-light bg-light">
	<a class="navbar-brand" href="{% url 'trans19:index' %}">Trans-19</a>
	<button class="navbar-toggler" data-toggle="collapse" data-target="#navLinks" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navLinks">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item {{ patient_tab }}">
          <a class="nav-link" href="{% url 'trans19:patients' %}">Patients</a>
        </li>
        <li class="nav-item {{ location_tab }}">
          <a class="nav-link" href="{% url 'trans19:locations' %}">Locations</a>
        </li>
        <li class="nav-item {{ new_patient_tab }}">
          <a class="nav-link" href="{% url 'trans19:patient_new' %}">Add Patient</a>
        </li>
        <li class="nav-item {{ new_location_tab }}">
          <a class="nav-link" href="{% url 'trans19:location_new' %}">Add Location</a>
        </li>
        <li class="nav-item {{ connection_tab }}">
          <a class="nav-link" href="{% url 'trans19:search_connections' %}">Connections</a>
        </li>
      </ul>
      
      {% if user.is_authenticated %}
        <button class="nav-item login_btn" onclick="location.href ='{% url 'logout'%}'" title="Logout">
          {% include "trans19/svgs/usernameSvg.html" %} {% if user.get_name %} {{ user.get_name }} {% else %} {{user.get_username}} {% endif %}
        </button>
      {% else %}
        <button class="nav-item nav_login_btn" style="float: right;">
          <a class="nav-link" href="{% url 'login' %}" style="color: rgb(255, 255, 255);">
            {% include 'trans19/svgs/loginSvg.html' %} Login
          </a>
        </button>
      {% endif %} 
    </div>
  </nav>