mysite/urls.py
from django.contrib import admin
from django.urls import include, path
# from django.views.generic import RedirectView

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("trans19.urls")),
    path('accounts/', include('django.contrib.auth.urls')),
]

trans19/urls.py
from django.urls import path
from . import views

app_name = 'trans19'

urlpatterns = [
    path('', views.index, name='index'),
    path('locations/', views.locations, name='locations'),
    path('patients/', views.patients, name='patients'),
    path('patients/<int:patient_id>/', views.detail, name='detail'),
    path('patients/new/', views.PatientCreate.as_view(), name='patient_new'),
    path('patients/<int:pk>/edit', views.PatientUpdate.as_view(), name='patient_edit'),
    path('patients/<int:pk>/delete', views.PatientDelete.as_view(), name='patient_delete'),
    path('patients/search/', views.SearchConnectionsView, name='search_connections'),
    path('locations/new', views.location_new, name='location_new'),
    path('locations/<int:pk>/edit', views.location_edit, name='location_edit'),
    path('locations/<int:pk>/delete', views.LocationDelete.as_view(), name='location_delete'),
]

trans19/models.py
from django.db import models
from django.urls import reverse
from datetime import date

class Patient(models.Model):
  patient_name = models.CharField(
    "Name", 
    max_length=200, 
    # help_text="Name of the Patient"
  )
  patient_id = models.CharField(
    "Patient Identity Document Number", 
    max_length=10, 
    # help_text="Identity Document Number", 
    null=True, 
    blank=True
  )
  date_of_birth = models.DateField(
    "Date of Birth", 
    null=True, 
    blank=True
  )
  date_case_confirmed = models.DateField(
    "Date Case Confirmed", 
    null=False, 
    blank=False, 
    default=date.today
  )
  case_number = models.IntegerField(
    "Case Number", 
    primary_key=True,
    null=False,
    blank=False, 
    # default=0, #Patient.objects.all().count(),
    # help_text="The case number of the Patient"
  )

  def __str__(self):
    return self.patient_name+" #"+str(self.case_number)

  def get_absolute_url(self):
      """Returns the url to access a particular author instance."""
      return reverse('detail', args=[str(self.case_number)])

class Location(models.Model):
  location_name = models.CharField("Location Visited", max_length=200, help_text="Name of the Location", blank=True)
  DISTRICT_CHOICES = [
    ('Hong Kong Island', (
            ('Central and Western', 'Central and Western'),
            ('Eastern', 'Eastern'),
            ('Southern', 'Southern'),
            ('Wan Chai', 'Wan Chai'),
        )
    ),
    ('Kowloon', (
            ('Sham Shui Po', 'Sham Shui Po'),
            ('Kowloon City', 'Kowloon City'),
            ('Kwun Tong', 'Kwun Tong'),
            ('Wong Tai Sin', 'Wong Tai Sin'),
            ('Yau Tsim Mong', 'Yau Tsim Mong'),
        )
    ),
    ('New Teritories', (
            ('Islands', 'Islands'),
            ('Kwai Tsing', 'Kwai Tsing'),
            ('North', 'North'),
            ('Sai Kung', 'Sai Kung'),
            ('Sha Tin', 'Sha Tin'),
            ('Tai Po', 'Tai Po'),
            ('Tsuen Wan', 'Tsuen Wan'),
            ('Tuen Mun', 'Tuen Mun'),
            ('Yuen Long', 'Yuen Long'),
        )
    ),
  ]
  district = models.CharField("District", max_length=200, choices=DISTRICT_CHOICES , help_text="District of the Location", default="Central and Western")
  address = models.CharField("Address", max_length=200, help_text="Address of the Location", blank=True, null=True)
  x_coord = models.FloatField("X Coord", help_text="X Coordiates/Longitude of the location", default=0)
  y_coord = models.FloatField("Y Coord", help_text="Y Coordiates/Latitude of the location", default=0)
  def __str__(self):
    return self.location_name

class Visit(models.Model):
  patient = models.ForeignKey(Patient, on_delete=models.CASCADE)
  location = models.ForeignKey(Location, on_delete=models.CASCADE)
  date_from = models.DateField("Date From", default=date.today)
  date_to = models.DateField("Date To", default=date.today)
  detail = models.CharField(max_length=65536, null=True, blank=True)
  CATEGORY_CHOICES = (
    (u'r', u'Residence'),
    (u'w', u'Workplace'),
    (u'v', u'Visit'),
    (u's', u'School'),
  )
  category = models.CharField("Category", max_length=1, choices=CATEGORY_CHOICES, default="v")
  def __str__(self):
    return self.location.location_name+" ("+str(self.date_from)+" - "+str(self.date_to)+")"
  def get_absolute_url(self):
    return reverse('travelhistory-detail', args=[str(self.id)])

trans19/forms.py
from django import forms
from .models import Patient, Visit, Location
from django.forms import inlineformset_factory
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Layout, Field, Fieldset, Div, HTML, ButtonHolder, Submit
from .custom_layout_object import *


class LocationForm(forms.ModelForm):
    class Meta:
        model = Location
        fields = '__all__'


class DateInput(forms.DateInput):
    input_type = 'date'


class VisitForm(forms.ModelForm):
    class Meta:
        model = Visit
        fields = '__all__'
        widgets = {
            'date_from': DateInput(),
            'date_to': DateInput(),
        }


PatientFormSet = inlineformset_factory(
    Patient,
    Visit,
    form=VisitForm,
    extra=1,
    can_delete=True,
)


class PatientForm(forms.ModelForm):

    class Meta:
        model = Patient
        exclude = ()
        widgets = {
            'date_case_confirmed': DateInput(),
            'date_of_birth': DateInput(),
        }

    def __init__(self, *args, **kwargs):
        super(PatientForm, self).__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.form_tag = True
        self.helper.form_class = 'form-horizontal'
        self.helper.label_class = 'col-md-3 create-label'
        self.helper.field_class = 'col-md-9'
        self.helper.layout = Layout(
            Div(
                Field('patient_name'),
                Field('patient_id'),
                Field('date_of_birth'),
                Field('date_case_confirmed'),
                Field('case_number'),
                Fieldset('Add Visits',
                        Formset('visits')),
                HTML("<br>"),
                ButtonHolder(Submit('submit', 'Save')),
                )
            )

trans19/views.py
from django.shortcuts import get_object_or_404, render, redirect
from django.urls import reverse_lazy
from django.db import transaction
from django.views.generic.edit import CreateView, UpdateView, DeleteView


from .models import Patient, Location, Visit
from .forms import LocationForm, PatientForm, PatientFormSet

from datetime import timedelta

def index(request):
    num_cases = Patient.objects.all().count()
    context = {"num_cases": num_cases, "index": "active"}
    return render(request, 'trans19/index.html', context)


def locations(request):
    latest_location_list = Location.objects.order_by('location_name')[:20]
    context = {'latest_location_list': latest_location_list, "location_tab": "active"}
    return render(request, 'trans19/locations.html', context)


def patients(request):
    latest_patient_list = Patient.objects.order_by('case_number')[:20]
    context = {'latest_patient_list': latest_patient_list, "patient_tab": "active"}
    return render(request, 'trans19/patients.html', context)


def detail(request, patient_id):
    patient = get_object_or_404(Patient, pk=patient_id)
    return render(request, 'trans19/detail.html', {'patient': patient})


def location_new(request):
    if request.method == "POST":
        form = LocationForm(request.POST)
        if form.is_valid():
            location = form.save(commit=False)
            location.save()
            return redirect('trans19:locations')
    else:
        form = LocationForm()
    return render(request, 'trans19/addLocation.html', {'form': form, "new_location_tab": "active"})


def location_edit(request, pk):
    location = get_object_or_404(Location, pk=pk)
    if request.method == "POST":
        form = LocationForm(request.POST, instance=location)
        if form.is_valid():
            location = form.save(commit=False)
            location.save()
            return redirect('trans19:locations')
    else:
        form = LocationForm(instance=location)
    return render(request, 'trans19/addLocation.html', {'form': form})


class LocationDelete(DeleteView):
    model = Location
    template_name = 'trans19/deleteLocation.html'
    success_url = reverse_lazy('trans19:locations')


class PatientCreate(CreateView):
    model = Patient
    template_name = 'trans19/addPatient.html'
    form_class = PatientForm
    success_url = None

    def get_context_data(self, **kwargs):
        data = super(PatientCreate, self).get_context_data(**kwargs)
        if self.request.POST:
            data['visits'] = PatientFormSet(self.request.POST)
        else:
            data['visits'] = PatientFormSet()
        data["new_patient_tab"] = "active"
        data['form'] = PatientForm(initial={"case_number": Patient.objects.all().count()})
        return data

    def form_valid(self, form):
        context = self.get_context_data()
        visits = context['visits']
        with transaction.atomic():
            form.instance.created_by = self.request.user
            self.object = form.save()
            if visits.is_valid():
                visits.instance = self.object
                visits.save()
        return super(PatientCreate, self).form_valid(form)

    def get_success_url(self):
        return reverse_lazy('trans19:patients')


class PatientUpdate(UpdateView):
    model = Patient
    template_name = 'trans19/addPatient.html'
    form_class = PatientForm

    def get_context_data(self, **kwargs):
        data = super(PatientUpdate, self).get_context_data(**kwargs)
        if self.request.POST:
            data['visits'] = PatientFormSet(self.request.POST, instance=self.object)
        else:
            data['visits'] = PatientFormSet(instance=self.object)
        return data

    def form_valid(self, form):
        context = self.get_context_data()
        visits = context['visits']
        with transaction.atomic():
            form.instance.created_by = self.request.user
            self.object = form.save()
            if visits.is_valid():
                visits.instance = self.object
                visits.save()
        return super(PatientUpdate, self).form_valid(form)

    def get_success_url(self):
        return reverse_lazy('trans19:patients')


class PatientDelete(DeleteView):
    model = Patient
    template_name = 'trans19/deletePatient.html'
    success_url = reverse_lazy('trans19:patients')


def SearchConnectionsView(request):
    patient_case = request.GET.get('case_number')
    time_window = request.GET.get('time_window')
    if time_window:
        time_window = int(time_window)
    context = {"patient": patient_case, "connection_tab": "active"}
    unfortunate_list = Visit.objects.none()
    visit_list = Visit.objects.filter(patient__case_number=patient_case).values(
        "location", "date_from", "date_to")
    for v in visit_list:
        unfortunate_list = unfortunate_list | Visit.objects.filter(
            location=v["location"]
            ).filter(
                date_from__range=(
                    v["date_from"] - timedelta(days=time_window),
                    v["date_to"] + timedelta(days=time_window)
                )
            ) | Visit.objects.filter(
                location=v["location"]).filter(date_to__range=(
                    v["date_from"] - timedelta(days=time_window),
                    v["date_to"] + timedelta(days=time_window)
                )
            )
    context['potential_patient_list'] = unfortunate_list.exclude( patient__case_number=patient_case)
    context['selected_patient'] = Patient.objects.filter(case_number=patient_case).values( "patient_name", "date_case_confirmed", "case_number")
    context['selected_patient_visit'] = Visit.objects.filter(patient__case_number=patient_case)

    return render(request, 'trans19/searchConnections.html', context)

trans19/templates/trans19/addLocation.html
{% extends "trans19/layouts/base.html" %}
{% block title %}
Add Location
{% endblock %}

{% block content %}
    <div class="container-fluid my-5">
        <div class="card">
            <div class="card-header">
                Add Location
            </div>
            <div class="card-body">
               <form method="POST">{% csrf_token %}
                {{ form.as_p }}
                <button type="submit" class="save btn btn-primary">Save</button>
                </form>
            </div>
        </div>
    </div>
{% endblock %}

trans19/templates/trans19/addPatient.html
{% extends "trans19/layouts/base.html" %}
{% block title %}
Add Patient
{% endblock %}
{% load crispy_forms_tags %}

{% block content %}

    <div class="container-fluid my-5">
        <div class="card">
            <div class="card-header">
                Add Patient
            </div>
            <div class="card-body">
                {% crispy form %}
            </div>
        </div>
    </div>

{% endblock %}

trans19/templates/trans19/deleteLocation.html
{% extends "trans19/layouts/base.html" %}
{% block title %}
Delete Location
{% endblock %}
{% block content %}
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h3 class="modal-title">Confirm Delete</h3>
            </div>
            <div class="modal-body">
                <form action="" method="post">
                    {% csrf_token %}
                    <h4>
                        Are you sure you want to delete location: <strong>{{ object }}</strong>?
                    </h4>
                    <input  class="btn btn-danger" type="submit" value="Yes, I want to delete" />
                </form>
            </div>
            <div class="modal-footer">
                <input  class="btn btn-outline-secondary" type="submit" value="Cancel" onclick="goBack()" />
            </div>
        </div>
    </div>
    <script>
        function goBack() {
            window.history.back();
        }
    </script>
{% endblock content %}

trans19/templates/trans19/deletePatient.html
{% extends "trans19/layouts/base.html" %}
{% block title %}
Delete Patient
{% endblock %}
{% block content %}
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h3 class="modal-title">Confirm Delete</h3>
            </div>
            <div class="modal-body">
                <form action="" method="post">
                    {% csrf_token %}
                    <h4>
                        Are you sure you want to delete <strong>{{ object }}'s</strong> patient record?
                    </h4>
                    <input  class="btn btn-danger" type="submit" value="Yes, I want to delete" />
                </form>
            </div>
            <div class="modal-footer">
                <input  class="btn btn-outline-secondary" type="submit" value="Cancel" onclick="goBack()" />
            </div>
        </div>
    </div>
    <script>
        function goBack() {
            window.history.back();
        }
    </script>
{% endblock content %}

trans19/templates/trans19/detail.html
{% extends "trans19/layouts/base.html" %}
{% block content %}
    <h2 class="text-center mt-5">Case {{ patient.case_number }}: {{ patient.patient_name }}</h2>
    <h4 class="text-center">Visit Record</h4>
    <table>
        <tr>
            <th class="header">Location Visited</th>
            <th class="header">Date from</th>
            <th class="header">Date to</th>
            <th class="header">Detail</th>
            <th class="header">Category</th>
        </tr>
        {% for visit in patient.visit_set.all %}
        <tr>
            <th>{{ visit }}</th>
            <th>{{ visit.date_from }}</th>
            <th>{{ visit.date_to }}</th>
            <th>{{ visit.detail }}</th>
            <th>{{ visit.category }}</th>
        </tr>
        {% endfor %}
    </table>
{% endblock %}

trans19/templates/trans19/formset.html
{% load crispy_forms_tags %}
{% load static %}

<div class="table-responsive">

<table class="mt-1 float-left table table-bordered table-sm">
{{ formset.management_form|crispy }}
    <tbody class="formset_row-{{ formset.prefix }}">
        {% for form in formset.forms %}
            <tr>
                {% for field in form.visible_fields %}
                    <td>
                        {% if forloop.first %}
                            {% for hidden in form.hidden_fields %}
                                {{ hidden }}
                            {% endfor %}
                        {% endif %}
                    {{ field.errors.as_ul }}
                    {{ field|as_crispy_field }}
                    </td>
                 {% endfor %}
            </tr>
        {% endfor %}
    </tbody>
</table>
</div>
<script src="//ajax.googleapis.com/ajax/libs/jquery/2.1.3/jquery.min.js"></script>
<script src="{% static "dynamic_formsets/jquery.formset.js" %}" type="text/javascript"> </script>
<script type="text/javascript">
    $('.formset_row-{{ formset.prefix }}').formset({
        addText: 'add another',
        deleteText: 'remove',
        prefix: '{{ formset.prefix }}',
    });
</script>

trans19/templates/trans19/index.html
{% extends "trans19/layouts/base.html" %}
{% block title %}
Index
{% endblock %}
{% block content %}
    <div class="container mt-5">
        <h1 class="display-4">Trans-19</h1>
        <p class="lead pt-2 pl-2">A web application to keep track of the database of Covid-19 Patients at CHP</p>
        <strong>Number of cases: {{ num_cases }}</strong>
    </div>
{% endblock %}

trans19/templates/trans19/locations.html
{% extends "trans19/layouts/base.html" %}
{% block title %}
Locations list
{% endblock %}
{% block content %}
    <h2 class="text-center mt-5">Location Record</h2>
    <table>
            <tr>
                <th class="header">Locations</th>
                <th class="header">Address</th>
                <th class="header">District</th>
                <th class="header">X Coord</th>
                <th class="header">Y Coord</th>
                <th class="header">Modify</th>
            </tr>
            {% for location in latest_location_list %}
            <tr>
                <th>{{ location }}</th>
                <th>{{ location.address }}</th>
                <th>{{ location.district }}</th>
                <th>{{ location.x_coord }}</th>
                <th>{{ location.y_coord }}</th>
                <th>
                    <a href="{% url 'trans19:location_edit' pk=location.pk %}">Edit</a>
                    <a href="{% url 'trans19:location_delete' pk=location.pk %}">Delete</a>
                </th>
            </tr>
            {% endfor %}
    </table>
{% endblock %}

trans19/templates/trans19/patients.html
{% extends "trans19/layouts/base.html" %}
{% block title %}
Patient list
{% endblock %}
{% block content %}
    <h2 class="text-center mt-5">Patient Record</h2>
    {%  if latest_patient_list %}
    <table>
            <tr>
                <th class="header">Patient Name</th>
                <th class="header">ID number</th>
                <th class="header">Date of birth</th>
                <th class="header">Date case confirmed</th>
                <th class="header">Case number</th>
                <th class="header">Location(s) Visited</th>
                <th class="header">Modify</th>
            </tr>
            {% for patient in latest_patient_list %}
            <tr>
                <td>{{ patient.patient_name }}</td>
                <td>{{ patient.patient_id }}</td>
                <td>{{ patient.date_of_birtd }}</td>
                <td>{{ patient.date_case_confirmed }}</td>
                <td>{{ patient.case_number }}</td>
                <td><a href="{% url 'trans19:detail' patient.case_number %}">Visit Record</a></td>
                <td>
                    <a href="{% url 'trans19:patient_edit' pk=patient.pk %}">Edit</a>
                    <a href="{% url 'trans19:patient_delete' pk=patient.pk %}">Delete</a>
                </td>
            </tr>
            {% endfor %}
    </table>
    {%  else %}
        <p>No patients are available.</p>
    {%  endif %}
{% endblock %}

trans19/templates/trans19/searchConnections.html
{% extends "trans19/layouts/base.html" %}
{% block title %}
Search Connections
{% endblock %}
{% block content %}
<div class="container-fluid my-5">
  <div class="card">
    <div class="card-header">
      Search Connections
    </div>
    <div class="card-body">
      <form method="GET">
        {% csrf_token %}
        <p>
          <label for="id_patient_case">Patient Case Number:</label>
          <input
            type="number"
            name="case_number"
            class="numberinput"
            required=""
            value="0"
            min="0"
            id="id_patient_case"
          />
        </p>

        <p>
          <label for="id_time_window">Time WIndow:</label>
          <input
            type="number"
            name="time_window"
            class="numberinput"
            required=""
            value="0"
            min="0"
            id="id_time_window"
          />
        </p>

        <button type="submit" class="save btn btn-primary">Search</button>
      </form>
    </div>
  </div>
</div>
{% if selected_patient %}
<h1 class="text-center mt-5">Search Results</h1>

<h3 class="text-center mt-5">Selected Patient</h3>
<table>
  <tr>
    <th class="header">Case number</th>
    <th class="header">Patient Name</th>
    <th class="header">Date case confirmed</th>
  </tr>
  <tr>
    {% for patient in selected_patient %}
    <td>{{ patient.case_number }}</td>
    <td>{{ patient.patient_name }}</td>
    <td>{{ patient.date_case_confirmed }}</td>
    {% endfor %}
  </tr>
</table>

<h3 class="text-center mt-5">Selected Patient's Visits</h3>
<table>
  <tr>
    <th class="header">Location Visited</th>
    <th class="header">Address</th>
    <th class="header">District</th>
    <th class="header">X Coord</th>
    <th class="header">Y Coord</th>
    <th class="header">Date From</th>
    <th class="header">Date To</th>
    <th class="header">Detail</th>
    <th class="header">Category</th>
  </tr>

  {% for visit in selected_patient_visit %}
  <tr>
    <td>
      {{ visit.location.location_name }}
    </td>
    <td>
      {{ visit.location.address }}
    </td>
    <td>
      {{ visit.location.district }}
    </td>
    <td>
      {{ visit.location.x_coord }}
    </td>
    <td>
      {{ visit.location.y_coord }}
    </td>
    <td>
      {{ visit.date_from }}
    </td>
    <td>
      {{ visit.date_to }}
    </td>
    <td>
      {{ visit.details }}
    </td>
    <td>
      {{ visit.category }}
    </td>
  </tr>
  {% endfor %}
</table>

<h3 class="text-center mt-5">Possible Connections to the Selected Patient</h3>
<table>
  <tr>
    <th class="header">Case Number</th>
    <th class="header">Patient Name</th>
    <th class="header">Date case confirmed</th>
    <th class="header">Location</th>
    <th class="header">Date From</th>
    <th class="header">Date To</th>
    <th class="header">Detail</th>
    <th class="header">Category</th>
  </tr>
  {% for visit in potential_patient_list %}
  <tr>
    <td>{{ visit.patient.case_number }}</td>
    <td>{{ visit.patient.patient_name }}</td>
    <td>{{ visit.patient.date_case_confirmed }}</td>
    <td>{{ visit.location.location_name }}</td>
    <td>{{ visit.date_from }}</td>
    <td>{{ visit.date_to }}</td>
    <td>{{ visit.details }}</td>
    <td>{{ visit.category }}</td>
  </tr>
  {% endfor %}
</table>
{% endif %}
<br />
{% endblock %}